INSERT INTO `ds_category` VALUES('77','1','content','0','1','44','0,44','0','77','产业','','','','youxi/','chanye','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=77','51','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','77','1','0','chanye','');
INSERT INTO `ds_category` VALUES('78','1','content','0','1','44','0,44','0','78','攻略','','','','youxi/','gonglue','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=78','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','78','1','0','gonglue','');
INSERT INTO `ds_category` VALUES('79','1','content','0','1','44','0,44','0','79','视野','','','','youxi/','shiye','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=79','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','79','1','0','shiye','');
INSERT INTO `ds_category` VALUES('59','1','content','0','1','40','0,40','0','59','国内','','','','qiye/','guonei','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=59','51','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','59','1','0','guonei','');
INSERT INTO `ds_category` VALUES('60','1','content','0','1','40','0,40','0','60','国际','','','','qiye/','guoji','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=60','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','60','1','0','guoji','');
INSERT INTO `ds_category` VALUES('61','1','content','0','1','40','0,40','0','61','公益','','','','qiye/','gongyi','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=61','20','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','61','1','0','gongyi','');
INSERT INTO `ds_category` VALUES('62','1','content','0','1','40','0,40','0','62','创业','','','','qiye/','chuangye','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=62','2','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','62','1','0','chuangye','');
INSERT INTO `ds_category` VALUES('74','1','content','0','1','43','0,43','0','74','通讯','','','','keji/','tongxun','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=74','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','74','1','0','tongxun','');
INSERT INTO `ds_category` VALUES('18','1','content','0','1','0','0','1','18,19,20','联系我们','','','','','LXWM','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=18','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category_content\",\"list_template\":\"list_about\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','19','0','0','lianxiwomen','');
INSERT INTO `ds_category` VALUES('19','1','content','0','1','18','0,18','0','19','联系方式','','','','LXWM/','LXFS','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=19','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_content\',
  \'list_template\' => \'list_about\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','20','1','0','lianxifangshi','');
INSERT INTO `ds_category` VALUES('20','1','content','0','1','18','0,18','0','20','招聘英才','','','','LXWM/','ZPYC','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=20','1','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category_content\',
  \'list_template\' => \'list_about\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','21','1','0','zhaopinyingcai','');
INSERT INTO `ds_category` VALUES('76','1','content','0','1','44','0,44','0','76','测评','','','','youxi/','ceping','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=76','49','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','76','1','0','ceping','');
INSERT INTO `ds_category` VALUES('75','1','content','0','1','43','0,43','0','75','新能源','','','','keji/','xinnengyuan','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=75','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','75','1','0','xinnengyuan','');
INSERT INTO `ds_category` VALUES('66','1','content','0','1','41','0,41','0','66','金融','','','','caijing/','jinrong','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=66','20','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','66','1','0','jinrong','');
INSERT INTO `ds_category` VALUES('65','1','content','0','1','41','0,41','0','65','基金','','','','caijing/','jijin','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=65','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','65','1','0','jijin','');
INSERT INTO `ds_category` VALUES('81','1','content','0','1','44','0,44','0','81','国内','','','','/','guonei','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=81','20','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','81','1','0','guonei','');
INSERT INTO `ds_category` VALUES('63','1','content','0','1','41','0,41','0','63','国际','','','','caijing/','guoji','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=63','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','63','1','0','guoji','');
INSERT INTO `ds_category` VALUES('64','1','content','0','1','41','0,41','0','64','股票','','','','caijing/','gupiao','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=64','20','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','64','1','0','gupiao','');
INSERT INTO `ds_category` VALUES('72','1','content','0','1','43','0,43','0','72','智能','','','','keji/','zhineng','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=72','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','72','1','0','zhineng','');
INSERT INTO `ds_category` VALUES('73','1','content','0','1','43','0,43','0','73','数码','','','','keji/','yidong','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=73','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','73','1','0','shuma','');
INSERT INTO `ds_category` VALUES('70','1','content','0','1','42','0,42','0','70','数码','','','','shenghuo/','shuma','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=70','47','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','70','1','0','shuma','');
INSERT INTO `ds_category` VALUES('71','1','content','0','1','42','0,42','0','71','汽车','','','','shenghuo/','qiche','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=71','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','71','1','0','qiche','');
INSERT INTO `ds_category` VALUES('69','1','content','0','1','42','0,42','0','69','家居','','','','shenghuo/','jiaju','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=69','46','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','69','1','0','jiaju','');
INSERT INTO `ds_category` VALUES('67','1','content','0','1','42','0,42','0','67','教育','','','','shenghuo/','jiaoyu','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=67','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','67','1','0','jiaoyu','');
INSERT INTO `ds_category` VALUES('68','1','content','0','1','42','0,42','0','68','房产','','','','shenghuo/','fangchan','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=68','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','68','1','0','fangchan','');
INSERT INTO `ds_category` VALUES('80','1','content','0','1','0','0','0','80','专题','','','','','zhuanti','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=80','1','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','80','0','0','zhuanti','');
INSERT INTO `ds_category` VALUES('40','1','content','0','1','0','0','1','40,59,60,61,62','企业','','','','','qiye','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=40','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','40','1','0','qiye','');
INSERT INTO `ds_category` VALUES('41','1','content','0','1','0','0','1','41,63,64,65,66','财经','','','','','caijing','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=41','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','41','1','0','caijing','');
INSERT INTO `ds_category` VALUES('42','1','content','0','1','0','0','1','42,67,68,69,70,71','生活','','','','','shenghuo','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=42','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','42','1','0','shenghuo','');
INSERT INTO `ds_category` VALUES('43','1','content','0','1','0','0','1','43,72,73,74,75','科技','','','','','keji','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=43','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','43','1','0','keji','');
INSERT INTO `ds_category` VALUES('44','1','content','0','1','0','0','1','44,81,76,77,78,79','游戏','','','','','youxi','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=44','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','44','1','0','youxi','');
INSERT INTO `ds_category` VALUES('45','1','content','0','1','0','0','1','45,46,47,48,49,50,51,52,53,54,55,56,57,58','江苏','','','','','jiangsu','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=45','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','45','1','0','jiangsu','');
INSERT INTO `ds_category` VALUES('46','1','content','0','1','45','0,45','0','46','南京','','','','jiangsu/','nanjing','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=46','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','46','1','0','nanjing','');
INSERT INTO `ds_category` VALUES('47','1','content','0','1','45','0,45','0','47','无锡','','','','jiangsu/','wuxi','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=47','20','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','47','1','0','wuxi','');
INSERT INTO `ds_category` VALUES('48','1','content','0','1','45','0,45','0','48','苏州','','','','jiangsu/','suzhou','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=48','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','48','1','0','suzhou','');
INSERT INTO `ds_category` VALUES('49','1','content','0','1','45','0,45','0','49','南通','','','','jiangsu/','nantong','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=49','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','49','1','0','nantong','');
INSERT INTO `ds_category` VALUES('50','1','content','0','1','45','0,45','0','50','常州','','','','jiangsu/','changzhou','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=50','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','50','1','0','changzhou','');
INSERT INTO `ds_category` VALUES('51','1','content','0','1','45','0,45','0','51','徐州','','','','jiangsu/','xuzhou','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=51','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','51','1','0','xuzhou','');
INSERT INTO `ds_category` VALUES('52','1','content','0','1','45','0,45','0','52','盐城','','','','jiangsu/','yancheng','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=52','20','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','52','1','0','yancheng','');
INSERT INTO `ds_category` VALUES('53','1','content','0','1','45','0,45','0','53','扬州','','','','jiangsu/','yangzhou','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=53','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','53','1','0','yangzhou','');
INSERT INTO `ds_category` VALUES('54','1','content','0','1','45','0,45','0','54','泰州','','','','jiangsu/','taizhou','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=54','0','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','54','1','0','taizhou','');
INSERT INTO `ds_category` VALUES('55','1','content','0','1','45','0,45','0','55','镇江','','','','jiangsu/','zhenjiang','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=55','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','55','1','0','zhenjiang','');
INSERT INTO `ds_category` VALUES('56','1','content','0','1','45','0,45','0','56','淮安','','','','jiangsu/','huaian','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=56','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','56','1','0','huaian','');
INSERT INTO `ds_category` VALUES('57','1','content','0','1','45','0,45','0','57','连云港','','','','jiangsu/','lianyungang','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=57','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','57','1','0','lianyungang','');
INSERT INTO `ds_category` VALUES('58','1','content','0','1','45','0,45','0','58','宿迁','','','','jiangsu/','suqian','http://localhost/jsrxsite/index.php?m=content&c=index&a=lists&catid=58','50','0','{\"workflowid\":\"\",\"ishtml\":\"0\",\"content_ishtml\":\"0\",\"create_to_html_root\":\"0\",\"template_list\":\"default\",\"category_template\":\"category\",\"list_template\":\"list\",\"show_template\":\"show\",\"meta_title\":\"\",\"meta_keywords\":\"\",\"meta_description\":\"\",\"presentpoint\":\"1\",\"defaultchargepoint\":\"0\",\"paytype\":\"0\",\"repeatchargedays\":\"1\",\"category_ruleid\":\"6\",\"show_ruleid\":\"16\"}','58','1','0','suqian','');
