<?php
return array (
  'varchar' => 
  array (
    'fieldid' => '109',
    'modelid' => '12',
    'siteid' => '1',
    'field' => 'varchar',
    'name' => '送餐时间',
    'tips' => '请选择送餐时间',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => '{"fieldtype":"datetime","format":"Y-m-d H:i:s","defaulttype":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'datetime',
    'format' => 'Y-m-d H:i:s',
    'defaulttype' => '0',
  ),
  'food' => 
  array (
    'fieldid' => '111',
    'modelid' => '12',
    'siteid' => '1',
    'field' => 'food',
    'name' => '食物',
    'tips' => '请选择喜欢的食物',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u897f\\u7ea2\\u67ff|fruit\\r\\n\\u9ec4\\u74dc|fruit\\r\\n\\u83dc\\u5934|fruit","boxtype":"select","fieldtype":"varchar","minnumber":"1","cols":"5","width":"80","size":"1","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '西红柿|fruit
黄瓜|fruit
菜头|fruit',
    'boxtype' => 'select',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
  ),
);
?>