<?php
return array (
  1415 => 
  array (
    'id' => '1415',
    'catid' => '5',
    'typeid' => '0',
    'title' => '徐泾镇：种文化 送文化 赛文化 好&ldquo;戏&rdquo;连台喜迎十九',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　红歌嘹亮，献礼祖国。近日，&ldquo;颂歌献给党   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=5&id=1415',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502783024',
    'updatetime' => '1503119292',
    'hitsid' => 'c-1-1415',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  1419 => 
  array (
    'id' => '1419',
    'catid' => '5',
    'typeid' => '0',
    'title' => '国网南平市延平区供电公司：开展教育扶贫 助力学子成长',
    'style' => '',
    'thumb' => 'http://fwimage.cnfanews.com/websiteimg/2017/20170808/34965/yxerhbniygs.jpg',
    'keywords' => '',
    'description' => '                                            　　国网南平市延平区供电公司:开展教育扶贫   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=5&id=1419',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502783025',
    'updatetime' => '1502900939',
    'hitsid' => 'c-1-1419',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>