<?php
return array (
  1414 => 
  array (
    'id' => '1414',
    'catid' => '4',
    'typeid' => '0',
    'title' => '美国智库统计显示南海是全球经济活动重要交汇点',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　参考消息网8月9日报道美媒称，多年来，各种文章、评论和分析都把每年5 3万亿美元贸易经过南海当作事实。然而，这个数字的来源向来是个谜。',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1414',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782705',
    'updatetime' => '1503119116',
    'hitsid' => 'c-1-1414',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1410 => 
  array (
    'id' => '1410',
    'catid' => '4',
    'typeid' => '0',
    'title' => '外媒：美军“封杀”中国产无人机理由“牵强”',
    'style' => '',
    'thumb' => 'http://fwimage.cnfanews.com/websiteimg/2017/20170809/34978/w020170809311176871965.jpg',
    'keywords' => '',
    'description' => '                                            　　参考消息网8月9日报道综合外媒报道称，美   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1410',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782704',
    'updatetime' => '1502804109',
    'hitsid' => 'c-1-1410',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1402 => 
  array (
    'id' => '1402',
    'catid' => '4',
    'typeid' => '0',
    'title' => '综述：中国技术助力古巴太阳能光伏板生产',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　新华社古巴比那尔德里奥8月7日电 综述：   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1402',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782703',
    'updatetime' => '1502782743',
    'hitsid' => 'c-1-1402',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  1399 => 
  array (
    'id' => '1399',
    'catid' => '4',
    'typeid' => '0',
    'title' => '中国汽车产业发展离不开“全球化”',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　随着中国国内小排量汽车购置税优惠政策的   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1399',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782703',
    'updatetime' => '1502782743',
    'hitsid' => 'c-1-1399',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  1398 => 
  array (
    'id' => '1398',
    'catid' => '4',
    'typeid' => '0',
    'title' => '特朗普搅动全球经济治理',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　特朗普当选美国总统以来，不断打破旧有执   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1398',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782703',
    'updatetime' => '1502782743',
    'hitsid' => 'c-1-1398',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  1397 => 
  array (
    'id' => '1397',
    'catid' => '4',
    'typeid' => '0',
    'title' => '韩媒称韩国零部件畅销中国 未受“萨德”影响',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　参考消息网8月9日报道 韩媒称，中国与世   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1397',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782703',
    'updatetime' => '1502782743',
    'hitsid' => 'c-1-1397',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  1396 => 
  array (
    'id' => '1396',
    'catid' => '4',
    'typeid' => '0',
    'title' => '华裔小夫妻仅花60万元买下旧金山富人区一条街',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　在美国旧金山，一套普通的房子售价超过10   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1396',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782702',
    'updatetime' => '1502782743',
    'hitsid' => 'c-1-1396',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  1395 => 
  array (
    'id' => '1395',
    'catid' => '4',
    'typeid' => '0',
    'title' => '通讯：中企投资孟加拉国实现双赢',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　新华社达卡8月8日电 通讯：中企投资孟加   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1395',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782702',
    'updatetime' => '1502782743',
    'hitsid' => 'c-1-1395',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  1394 => 
  array (
    'id' => '1394',
    'catid' => '4',
    'typeid' => '0',
    'title' => '日本学术界再现造假丑闻',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　日本东京大学日前表示，经过长达8个月的   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1394',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782702',
    'updatetime' => '1502782743',
    'hitsid' => 'c-1-1394',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  1393 => 
  array (
    'id' => '1393',
    'catid' => '4',
    'typeid' => '0',
    'title' => '中资公司完成对老挝电信公司股份收购交接',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '                                            　　据新华社万象8月8日电 （记者章建华）老   ',
    'posids' => '0',
    'url' => 'http://localhost/shuilisite/index.php?m=content&c=index&a=show&catid=4&id=1393',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1502782702',
    'updatetime' => '1502782743',
    'hitsid' => 'c-1-1393',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>